# Helping function for extracting fit parameters from each package, combining
# them together with standardized names. The results_photogea_alpha_new and
# results_pce_calculator input arguments can be set to NULL when this fit
# information is not required.
extract_fit_param <- function(
    results_photogea_alpha_old,
    results_photogea_alpha_new,
    results_plantecophys,
    results_photosynthesis,
    results_msu,
    results_pce_calculator,
    include_true_values,
    include_ppfd
)
{
    all_param <- data.frame(
        curve_identifier   = results_photogea_alpha_old[, 'curve_identifier'],
        ppfd               = if (include_ppfd) {results_photogea_alpha_old[, 'ppfd']} else {NA},
        true_n_Ac_limiting = if (include_true_values) {results_photogea_alpha_old[, 'true_n_Ac_limiting']} else {NA},
        true_n_Aj_limiting = if (include_true_values) {results_photogea_alpha_old[, 'true_n_Aj_limiting']} else {NA},
        true_n_Ap_limiting = if (include_true_values) {results_photogea_alpha_old[, 'true_n_Ap_limiting']} else {NA},
        true_RL            = if (include_true_values) {results_photogea_alpha_old[, 'true_RL_at_25']} else {NA},
        true_Vcmax         = if (include_true_values) {results_photogea_alpha_old[, 'true_Vcmax_at_25']} else {NA},
        true_J             = if (include_true_values) {results_photogea_alpha_old[, 'true_J_at_25']} else {NA},
        true_Tp            = if (include_true_values) {results_photogea_alpha_old[, 'true_Tp_at_25']} else {NA},
        true_alpha_old     = if (include_true_values) {results_photogea_alpha_old[, 'true_alpha_old']} else {NA},
        true_alpha_g       = if (include_true_values) {results_photogea_alpha_old[, 'true_alpha_g']} else {NA},
        true_alpha_s       = if (include_true_values) {results_photogea_alpha_old[, 'true_alpha_s']} else {NA},
        J                  = results_photogea_alpha_old[, 'J_tl_avg'],
        J_lower            = results_photogea_alpha_old[, 'J_tl_avg_lower'],
        J_upper            = results_photogea_alpha_old[, 'J_tl_avg_upper'],
        RL                 = results_photogea_alpha_old[, 'RL_tl_avg'],
        RL_lower           = results_photogea_alpha_old[, 'RL_tl_avg_lower'],
        RL_upper           = results_photogea_alpha_old[, 'RL_tl_avg_upper'],
        Tp                 = results_photogea_alpha_old[, 'Tp_tl_avg'],
        Tp_lower           = results_photogea_alpha_old[, 'Tp_tl_avg_lower'],
        Tp_upper           = results_photogea_alpha_old[, 'Tp_tl_avg_upper'],
        Vcmax              = results_photogea_alpha_old[, 'Vcmax_tl_avg'],
        Vcmax_lower        = results_photogea_alpha_old[, 'Vcmax_tl_avg_lower'],
        Vcmax_upper        = results_photogea_alpha_old[, 'Vcmax_tl_avg_upper'],
        alpha_old          = results_photogea_alpha_old[, 'alpha_old'],
        alpha_old_lower    = results_photogea_alpha_old[, 'alpha_old_lower'],
        alpha_old_upper    = results_photogea_alpha_old[, 'alpha_old_upper'],
        alpha_g            = results_photogea_alpha_old[, 'alpha_g'],
        alpha_g_lower      = results_photogea_alpha_old[, 'alpha_g_lower'],
        alpha_g_upper      = results_photogea_alpha_old[, 'alpha_g_upper'],
        alpha_s            = results_photogea_alpha_old[, 'alpha_s'],
        alpha_s_lower      = results_photogea_alpha_old[, 'alpha_s_lower'],
        alpha_s_upper      = results_photogea_alpha_old[, 'alpha_s_upper'],
        AIC                = results_photogea_alpha_old[, 'AIC'],
        RSS                = results_photogea_alpha_old[, 'RSS'],
        RMSE               = results_photogea_alpha_old[, 'RMSE'],
        package            = 'PhotoGEA'
    )

    if (!is.null(results_photogea_alpha_new)) {
        all_param <- rbind(
            all_param,
            data.frame(
                curve_identifier   = results_photogea_alpha_new[, 'curve_identifier'],
                ppfd               = if (include_ppfd) {results_photogea_alpha_new[, 'ppfd']} else {NA},
                true_n_Ac_limiting = if (include_true_values) {results_photogea_alpha_new[, 'true_n_Ac_limiting']} else {NA},
                true_n_Aj_limiting = if (include_true_values) {results_photogea_alpha_new[, 'true_n_Aj_limiting']} else {NA},
                true_n_Ap_limiting = if (include_true_values) {results_photogea_alpha_new[, 'true_n_Ap_limiting']} else {NA},
                true_RL            = if (include_true_values) {results_photogea_alpha_new[, 'true_RL_at_25']} else {NA},
                true_Vcmax         = if (include_true_values) {results_photogea_alpha_new[, 'true_Vcmax_at_25']} else {NA},
                true_J             = if (include_true_values) {results_photogea_alpha_new[, 'true_J_at_25']} else {NA},
                true_Tp            = if (include_true_values) {results_photogea_alpha_new[, 'true_Tp_at_25']} else {NA},
                true_alpha_old     = if (include_true_values) {results_photogea_alpha_new[, 'true_alpha_old']} else {NA},
                true_alpha_g       = if (include_true_values) {results_photogea_alpha_new[, 'true_alpha_g']} else {NA},
                true_alpha_s       = if (include_true_values) {results_photogea_alpha_new[, 'true_alpha_s']} else {NA},
                J                  = results_photogea_alpha_new[, 'J_tl_avg'],
                J_lower            = results_photogea_alpha_new[, 'J_tl_avg_lower'],
                J_upper            = results_photogea_alpha_new[, 'J_tl_avg_upper'],
                RL                 = results_photogea_alpha_new[, 'RL_tl_avg'],
                RL_lower           = results_photogea_alpha_new[, 'RL_tl_avg_lower'],
                RL_upper           = results_photogea_alpha_new[, 'RL_tl_avg_upper'],
                Tp                 = results_photogea_alpha_new[, 'Tp_tl_avg'],
                Tp_lower           = results_photogea_alpha_new[, 'Tp_tl_avg_lower'],
                Tp_upper           = results_photogea_alpha_new[, 'Tp_tl_avg_upper'],
                Vcmax              = results_photogea_alpha_new[, 'Vcmax_tl_avg'],
                Vcmax_lower        = results_photogea_alpha_new[, 'Vcmax_tl_avg_lower'],
                Vcmax_upper        = results_photogea_alpha_new[, 'Vcmax_tl_avg_upper'],
                alpha_old          = results_photogea_alpha_new[, 'alpha_old'],
                alpha_old_lower    = results_photogea_alpha_new[, 'alpha_old_lower'],
                alpha_old_upper    = results_photogea_alpha_new[, 'alpha_old_upper'],
                alpha_g            = results_photogea_alpha_new[, 'alpha_g'],
                alpha_g_lower      = results_photogea_alpha_new[, 'alpha_g_lower'],
                alpha_g_upper      = results_photogea_alpha_new[, 'alpha_g_upper'],
                alpha_s            = results_photogea_alpha_new[, 'alpha_s'],
                alpha_s_lower      = results_photogea_alpha_new[, 'alpha_s_lower'],
                alpha_s_upper      = results_photogea_alpha_new[, 'alpha_s_upper'],
                AIC                = results_photogea_alpha_new[, 'AIC'],
                RSS                = results_photogea_alpha_new[, 'RSS'],
                RMSE               = results_photogea_alpha_new[, 'RMSE'],
                package            = 'PhotoGEA (new alpha)'
            )
        )
    }

    if (!is.null(results_pce_calculator)) {
        all_param <- rbind(
            all_param,
            data.frame(
                curve_identifier   = results_pce_calculator[, 'curve_identifier'],
                ppfd               = if (include_ppfd) {results_pce_calculator[, 'ppfd']} else {NA},
                true_n_Ac_limiting = if (include_true_values) {results_pce_calculator[, 'true_n_Ac_limiting']} else {NA},
                true_n_Aj_limiting = if (include_true_values) {results_pce_calculator[, 'true_n_Aj_limiting']} else {NA},
                true_n_Ap_limiting = if (include_true_values) {results_pce_calculator[, 'true_n_Ap_limiting']} else {NA},
                true_RL            = if (include_true_values) {results_pce_calculator[, 'true_RL_at_25']} else {NA},
                true_Vcmax         = if (include_true_values) {results_pce_calculator[, 'true_Vcmax_at_25']} else {NA},
                true_J             = if (include_true_values) {results_pce_calculator[, 'true_J_at_25']} else {NA},
                true_Tp            = if (include_true_values) {results_pce_calculator[, 'true_Tp_at_25']} else {NA},
                true_alpha_old     = if (include_true_values) {results_pce_calculator[, 'true_alpha_old']} else {NA},
                true_alpha_g       = if (include_true_values) {results_pce_calculator[, 'true_alpha_g']} else {NA},
                true_alpha_s       = if (include_true_values) {results_pce_calculator[, 'true_alpha_s']} else {NA},
                J                  = results_pce_calculator[, 'J_tl'],
                J_lower            = results_pce_calculator[, 'J_tl_lower'],
                J_upper            = results_pce_calculator[, 'J_tl_upper'],
                RL                 = results_pce_calculator[, 'RL_tl'],
                RL_lower           = results_pce_calculator[, 'RL_tl_lower'],
                RL_upper           = results_pce_calculator[, 'RL_tl_upper'],
                Tp                 = results_pce_calculator[, 'Tp_tl'],
                Tp_lower           = results_pce_calculator[, 'Tp_tl_lower'],
                Tp_upper           = results_pce_calculator[, 'Tp_tl_upper'],
                Vcmax              = results_pce_calculator[, 'Vcmax_tl'],
                Vcmax_lower        = results_pce_calculator[, 'Vcmax_tl_lower'],
                Vcmax_upper        = results_pce_calculator[, 'Vcmax_tl_upper'],
                alpha_old          = results_pce_calculator[, 'alpha_old'],
                alpha_old_lower    = results_pce_calculator[, 'alpha_old_lower'],
                alpha_old_upper    = results_pce_calculator[, 'alpha_old_upper'],
                alpha_g            = NA,
                alpha_g_lower      = NA,
                alpha_g_upper      = NA,
                alpha_s            = NA,
                alpha_s_lower      = NA,
                alpha_s_upper      = NA,
                AIC                = results_pce_calculator[, 'AIC'],
                RSS                = results_pce_calculator[, 'RSS'],
                RMSE               = results_pce_calculator[, 'RMSE'],
                package            = 'PCE calculator'
            )
        )
    }

    all_param <- rbind(
        all_param,
        data.frame(
            curve_identifier   = results_plantecophys[, 'curve_identifier'],
            ppfd               = if (include_ppfd) {results_plantecophys[, 'ppfd']} else {NA},
            true_n_Ac_limiting = if (include_true_values) {results_plantecophys[, 'true_n_Ac_limiting']} else {NA},
            true_n_Aj_limiting = if (include_true_values) {results_plantecophys[, 'true_n_Aj_limiting']} else {NA},
            true_n_Ap_limiting = if (include_true_values) {results_plantecophys[, 'true_n_Ap_limiting']} else {NA},
            true_RL            = if (include_true_values) {results_plantecophys[, 'true_RL_at_25']} else {NA},
            true_Vcmax         = if (include_true_values) {results_plantecophys[, 'true_Vcmax_at_25']} else {NA},
            true_J             = if (include_true_values) {results_plantecophys[, 'true_J_at_25']} else {NA},
            true_Tp            = if (include_true_values) {results_plantecophys[, 'true_Tp_at_25']} else {NA},
            true_alpha_old     = if (include_true_values) {results_plantecophys[, 'true_alpha_old']} else {NA},
            true_alpha_g       = if (include_true_values) {results_plantecophys[, 'true_alpha_g']} else {NA},
            true_alpha_s       = if (include_true_values) {results_plantecophys[, 'true_alpha_s']} else {NA},
            J                  = results_plantecophys[, 'J'],
            J_lower            = results_plantecophys[, 'J_lower'],
            J_upper            = results_plantecophys[, 'J_upper'],
            RL                 = results_plantecophys[, 'Rd'],
            RL_lower           = results_plantecophys[, 'Rd_lower'],
            RL_upper           = results_plantecophys[, 'Rd_upper'],
            Tp                 = results_plantecophys[, 'TPU'],
            Tp_lower           = results_plantecophys[, 'TPU_lower'],
            Tp_upper           = results_plantecophys[, 'TPU_upper'],
            Vcmax              = results_plantecophys[, 'Vcmax'],
            Vcmax_lower        = results_plantecophys[, 'Vcmax_lower'],
            Vcmax_upper        = results_plantecophys[, 'Vcmax_upper'],
            alpha_old          = NA,
            alpha_old_lower    = NA,
            alpha_old_upper    = NA,
            alpha_g            = NA,
            alpha_g_lower      = NA,
            alpha_g_upper      = NA,
            alpha_s            = NA,
            alpha_s_lower      = NA,
            alpha_s_upper      = NA,
            AIC                = results_plantecophys[, 'AIC'],
            RSS                = results_plantecophys[, 'RSS'],
            RMSE               = results_plantecophys[, 'RMSE'],
            package            = 'plantecophys'
        ),
        data.frame(
            curve_identifier   = results_photosynthesis[, 'curve_identifier'],
            ppfd               = if (include_ppfd) {results_photosynthesis[, 'ppfd']} else {NA},
            true_n_Ac_limiting = if (include_true_values) {results_photosynthesis[, 'true_n_Ac_limiting']} else {NA},
            true_n_Aj_limiting = if (include_true_values) {results_photosynthesis[, 'true_n_Aj_limiting']} else {NA},
            true_n_Ap_limiting = if (include_true_values) {results_photosynthesis[, 'true_n_Ap_limiting']} else {NA},
            true_RL            = if (include_true_values) {results_photosynthesis[, 'true_RL_at_25']} else {NA},
            true_Vcmax         = if (include_true_values) {results_photosynthesis[, 'true_Vcmax_at_25']} else {NA},
            true_J             = if (include_true_values) {results_photosynthesis[, 'true_J_at_25']} else {NA},
            true_Tp            = if (include_true_values) {results_photosynthesis[, 'true_Tp_at_25']} else {NA},
            true_alpha_old     = if (include_true_values) {results_photosynthesis[, 'true_alpha_old']} else {NA},
            true_alpha_g       = if (include_true_values) {results_photosynthesis[, 'true_alpha_g']} else {NA},
            true_alpha_s       = if (include_true_values) {results_photosynthesis[, 'true_alpha_s']} else {NA},
            J                  = results_photosynthesis[, 'J'],
            J_lower            = results_photosynthesis[, 'J_lower'],
            J_upper            = results_photosynthesis[, 'J_upper'],
            RL                 = results_photosynthesis[, 'R_d'],
            RL_lower           = results_photosynthesis[, 'R_d_lower'],
            RL_upper           = results_photosynthesis[, 'R_d_upper'],
            Tp                 = results_photosynthesis[, 'V_TPU'],
            Tp_lower           = results_photosynthesis[, 'V_TPU_lower'],
            Tp_upper           = results_photosynthesis[, 'V_TPU_upper'],
            Vcmax              = results_photosynthesis[, 'V_cmax'],
            Vcmax_lower        = results_photosynthesis[, 'V_cmax_lower'],
            Vcmax_upper        = results_photosynthesis[, 'V_cmax_upper'],
            alpha_old          = NA,
            alpha_old_lower    = NA,
            alpha_old_upper    = NA,
            alpha_g            = NA,
            alpha_g_lower      = NA,
            alpha_g_upper      = NA,
            alpha_s            = NA,
            alpha_s_lower      = NA,
            alpha_s_upper      = NA,
            AIC                = results_photosynthesis[, 'AIC'],
            RSS                = results_photosynthesis[, 'RSS'],
            RMSE               = results_photosynthesis[, 'RMSE'],
            package            = 'photosynthesis'
        ),
        data.frame(
            curve_identifier   = results_msu[, 'curve_identifier'],
            ppfd               = if (include_ppfd) {results_msu[, 'ppfd']} else {NA},
            true_n_Ac_limiting = if (include_true_values) {results_msu[, 'true_n_Ac_limiting']} else {NA},
            true_n_Aj_limiting = if (include_true_values) {results_msu[, 'true_n_Aj_limiting']} else {NA},
            true_n_Ap_limiting = if (include_true_values) {results_msu[, 'true_n_Ap_limiting']} else {NA},
            true_RL            = if (include_true_values) {results_msu[, 'true_RL_at_25']} else {NA},
            true_Vcmax         = if (include_true_values) {results_msu[, 'true_Vcmax_at_25']} else {NA},
            true_J             = if (include_true_values) {results_msu[, 'true_J_at_25']} else {NA},
            true_Tp            = if (include_true_values) {results_msu[, 'true_Tp_at_25']} else {NA},
            true_alpha_old     = if (include_true_values) {results_msu[, 'true_alpha_old']} else {NA},
            true_alpha_g       = if (include_true_values) {results_msu[, 'true_alpha_g']} else {NA},
            true_alpha_s       = if (include_true_values) {results_msu[, 'true_alpha_s']} else {NA},
            J                  = results_msu[, 'J'],
            J_lower            = results_msu[, 'J_lower'],
            J_upper            = results_msu[, 'J_upper'],
            RL                 = results_msu[, 'rL'],
            RL_lower           = results_msu[, 'rL_lower'],
            RL_upper           = results_msu[, 'rL_upper'],
            Tp                 = results_msu[, 'TPU'],
            Tp_lower           = results_msu[, 'TPU_lower'],
            Tp_upper           = results_msu[, 'TPU'],
            Vcmax              = results_msu[, 'VcMax'],
            Vcmax_lower        = results_msu[, 'VcMax_lower'],
            Vcmax_upper        = results_msu[, 'VcMax_upper'],
            alpha_old          = NA,
            alpha_old_lower    = NA,
            alpha_old_upper    = NA,
            alpha_g            = results_msu[, 'ag'],
            alpha_g_lower      = NA,
            alpha_g_upper      = NA,
            alpha_s            = results_msu[, 'as'],
            alpha_s_lower      = NA,
            alpha_s_upper      = NA,
            AIC                = results_msu[, 'AIC'],
            RSS                = results_msu[, 'RSS'],
            RMSE               = results_msu[, 'RMSE'],
            package            = 'msuRACiFit'
        )
    )

    if (!include_true_values) {
        all_param$true_n_Ac_limiting <- NULL
        all_param$true_n_Aj_limiting <- NULL
        all_param$true_n_Ap_limiting <- NULL
        all_param$true_RL            <- NULL
        all_param$true_Vcmax         <- NULL
        all_param$true_J             <- NULL
        all_param$true_Tp            <- NULL
    }

    if (!include_ppfd) {
        all_param$ppfd <- NULL
    }

    all_param
}
